// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `exact_find_in_pattern`, `fix_string_case`, `get_rules`, `is_consonant`, `is_punctuation`, `is_vowel`, `match_non_rule_patterns`, `match_rule_patterns`, `parse_unicode`, `process_match`, `process_rules`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AvroRules`, `Data`, `MatchResult`, `Match`, `Meta`, `Pattern`, `Rule`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

String parseBangla({required String text, required bool bijoy}) => RustLib
    .instance
    .api
    .crateApiBanglaParserParseBangla(text: text, bijoy: bijoy);

String toBijoy({required String text}) =>
    RustLib.instance.api.crateApiBanglaParserToBijoy(text: text);

String toUnicode({required String text}) =>
    RustLib.instance.api.crateApiBanglaParserToUnicode(text: text);

String reverseBangla({required String text}) =>
    RustLib.instance.api.crateApiBanglaParserReverseBangla(text: text);

List<String> getAutocompleteSuggestions({
  required String partialText,
  required int maxSuggestions,
}) => RustLib.instance.api.crateApiBanglaParserGetAutocompleteSuggestions(
  partialText: partialText,
  maxSuggestions: maxSuggestions,
);
