// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<bool> isVowel({required String c}) =>
    RustLib.instance.api.crateApiBanglaUtilsIsVowel(c: c);

Future<bool> isConsonant({required String c}) =>
    RustLib.instance.api.crateApiBanglaUtilsIsConsonant(c: c);

Future<String> fixStringPattern({required String pattern}) =>
    RustLib.instance.api.crateApiBanglaUtilsFixStringPattern(pattern: pattern);

Future<String> handleLigatures({required String text}) =>
    RustLib.instance.api.crateApiBanglaUtilsHandleLigatures(text: text);

Future<String> handleMatra({required String text}) =>
    RustLib.instance.api.crateApiBanglaUtilsHandleMatra(text: text);

Future<String> handleZeroWidthChars({required String text}) =>
    RustLib.instance.api.crateApiBanglaUtilsHandleZeroWidthChars(text: text);

Future<(String, BigInt)> handleBackspaceCorrection({
  required String text,
  required BigInt cursorPos,
}) => RustLib.instance.api.crateApiBanglaUtilsHandleBackspaceCorrection(
  text: text,
  cursorPos: cursorPos,
);

Future<String> normalizeInput({required String text}) =>
    RustLib.instance.api.crateApiBanglaUtilsNormalizeInput(text: text);
